### ISSUE TITLE
Supporting behind separators

### ISSUE THREAD

**Issue by Vacxe** [imaNNeoFighT/StepBarView#1]
Could u add support for separators? Should be behind circles without gaps between them.

**Comment by imaNNeo** [comment]
i didn't understand.
may you explain more about it?

**Comment by Vacxe** [comment]
![screen shot 2561-05-18 at 11 10 59 am](https://user-images.githubusercontent.com/2812510/40215704-2fde204c-5a8c-11e8-89a2-bf0972334dfb.png)

Smth like that. Lines between circles should be behind.

**Comment by imaNNeo** [comment]
aha you mean the steps draw upon lines with a shadow,
i will do my best to implement this design,
(bit i'm not promise because i haven't enough time).
by the way i will try it.

**Comment by Vacxe** [comment]
Forget about shadows dude. It just a mock. Steps upon lines is enough

**Comment by imaNNeo** [comment]
<img src="https://im2.ezgif.com/tmp/ezgif-2-62c8bd83c1.gif" width=200/>
is it okay?

**Comment by Vacxe** [comment]
Its work well, but negative margins not the best solution. Thx!

**Comment by imaNNeo** [comment]
i know it's not the best solution,
But it's a fast hack.
