### ISSUE TITLE
View writes every step to logcat

### ISSUE THREAD

**Issue by bennernog** [imaNNeoFighT/StepBarView#2]
Thanks for sharing this widget, but the view writes every step to the log
`08-06 11:23:22.222 2866-2866/******.***.** D/SS: drawing 0 step
    drawing 1 step
    drawing 2 step
    drawing 3 step
    drawing 0 step
    drawing 1 step
    drawing 2 step
    drawing 3 step
    drawing 0 step
    drawing 1 step
    drawing 2 step
    drawing 3 step ...`

Since I'm using it in a list, this is seriously clogging up my logcat, which I use to test and debug my code. Please remove logging calls from library
Thank you

**Comment by imaNNeo** [comment]
Hi, i'm so glad that you are using my lib,
yes you'r right, i will remove the logs ASAP,
thanks for reporting.
