### ISSUE TITLE
Possibility to change the step by the button

### ISSUE THREAD

**Issue by alimemco** [imaNNeoFighT/StepBarView#7]
please add ability ,
 When the Button is clicked, the step moves to the desired position .

ex:
{
next.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                    RecyclerPosition++;
                    recyclerView.getLayoutManager().scrollToPosition(RecyclerPosition);

                              stepbarview.SetCurrentPosition(POSITION);
                             //and
                              stepbarview.ScrollToPosition(POSITION);

                
            }
        });

}

**Comment by imaNNeo** [comment]
You can change the current step by changing the 'reachedStep' property
